export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS';
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';

export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_BUS_STOPS_LIST = 'SET_BUS_STOPS_LIST';
export const SET_MAP_MODE = 'SET_MAP_MODE';
export const SET_SELECTED_MARKER = 'SET_SELECTED_MARKER';
export const SET_ROUTE_MAKER_LIST = 'SET_ROUTE_MAKER_LIST';
export const SET_ROUTE_PATH = 'SET_ROUTE_PATH';
export const SET_ROUTE_STATUS_LOADER = 'SET_ROUTE_STATUS_LOADER';
export const SET_ROUTE_LIST = 'SET_ROUTE_LIST';
export const SET_SAVED_ROUTE_PATH = 'SET_SAVED_ROUTE_PATH';