export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS';
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';

export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_BUS_STOPS_LIST = 'SET_BUS_STOPS_LIST';
export const SET_MAP_MODE = 'SET_MAP_MODE';